export const states = [
    { text: 'ABIA', value: 'abia' },
    { text: 'ABUJA FCT', value: 'abuja fct' },
    { text: 'ADAMAWA', value: 'adamawa' },
    { text: 'AKWA IBOM', value: 'akwa ibom' },
    { text: 'ANAMBRA', value: 'anambra' },
    { text: 'BAUCHI', value: 'bauchi' },
    { text: 'BAYELSA', value: 'bayelsa' },
    { text: 'BENUE', value: 'benue' },
    { text: 'BORNO', value: 'borno' },
    { text: 'CROSS RIVER', value: 'cross river' },
    { text: 'DELTA', value: 'delta' },
    { text: 'EBONYI', value: 'ebonyi' },
    { text: 'EDO', value: 'edo' },
    { text: 'EKITI', value: 'ekiti' },
    { text: 'ENUGU', value: 'enugu' },
    { text: 'GOMBE', value: 'gombe' },
    { text: 'IMO', value: 'imo' },
    { text: 'JIGAWA', value: 'jigawa' },
    { text: 'KADUNA', value: 'kaduna' },
    { text: 'KANO', value: 'kano' },
    { text: 'KATSINA', value: 'katsina' },
    { text: 'KEBBI', value: 'kebbi' },
    { text: 'KOGI', value: 'kogi' },
    { text: 'KWARA', value: 'kwara' },
    { text: 'LAGOS', value: 'lagos' },
    { text: 'NASARAWA', value: 'nasarawa' },
    { text: 'NIGER', value: 'niger' },
    { text: 'OGUN', value: 'ogun' },
    { text: 'ONDO', value: 'ondo' },
    { text: 'OSUN', value: 'osun' },
    { text: 'OYO', value: 'oyo' },
    { text: 'PLATEAU', value: 'plateau' },
    { text: 'RIVERS', value: 'rivers' },
    { text: 'SOKOTO', value: 'sokoto' },
    { text: 'TARABA', value: 'taraba' },
    { text: 'YOBE', value: 'yobe' },
    { text: 'ZAMFARA', value: 'zamfara' }
]
